// Theme configuration — edit this file to rebrand for your food event.
// After editing, run: python3 apply-theme.py
// This updates og-image, CNAME, HTML fallbacks, worker vars, and README.
//
// This file holds VALUES only. Behavior (event state, timezone math) lives
// in event-state.js, which is template-owned — don't add functions here.

const THEME = {
  // Event identity
  eventName: "SB Food Week 2026",
  eventDates: "TBD",
  emoji: "🍽️",

  // OG image text (two lines for the social preview image)
  ogLine1: "Santa Barbara",
  ogLine2: "Food Week 2026",

  // Labels (what to call the featured item)
  itemLabel: "item",
  itemLabelPlural: "items",

  // Site URL (used for OG meta tags, embed snippets, print page)
  siteUrl: "https://YOUR-DOMAIN.com",

  // Description (used for meta tags)
  description:
    "Interactive map of all participating restaurants. Search, filter by area, and get directions.",

  // Header — link to the source article announcing your event
  sourceLabel: "Source: Your Source",
  sourceUrl: "https://example.com/your-event-article",

  // Venmo tip jar (set venmoUser to null to hide the tip jar entirely)
  venmoUser: null,
  venmoNote: "Enjoyed the map?",

  // Tip jar tiers — size: "s" (custom emoji), "m" (half theme emoji), "l" (full theme emoji)
  // The "m" tier gets an orange featured border. Tracking events: tip-s, tip-m, tip-l
  tipTiers: [
    { size: "s", label: "Small Tip", emoji: "🪙", amount: 1 },
    { size: "m", label: "Medium Tip", amount: 5 },
    { size: "l", label: "Big Tip", amount: 10 },
  ],

  // LocalStorage namespace (unique per event to avoid collisions)
  storageKey: "sbfoodweek-checklist",

  // Print page
  printTitle: "SB Food Week 2026 — My Picks",

  // Event timezone — phase changes (pre/during/post) happen on this clock,
  // not the viewer's. IANA name, e.g. "America/Los_Angeles".
  timeZone: "America/Los_Angeles",

  // Event start date — used for analytics/stats time filters (ISO date)
  eventStartDate: null,

  // Event end date — concluded banner/modal auto-shows after this date (ISO date, null to never show)
  eventEndDate: null,

  // Archived — set true at wind-down (scripts/wind-down.py does this).
  // Drives the "off-season" state; trackUrl can stay set so the stats and
  // admin pages keep reading historical data from the Worker.
  archived: false,

  // Map center and zoom level — [latitude, longitude]
  mapCenter: [34.42, -119.7],
  mapZoom: 13,

  // GitHub repo URL (used in About modal and footer)
  githubRepoUrl: "https://github.com/YOUR_USERNAME/YOUR_REPO",

  // Data launch date — before this date, data.js (skeleton) loads.
  // On or after this date, data-<year>.js (full menu details) loads.
  // Format: "YYYY-MM-DD" in local time, activates at 12:01 AM. Set null to always load full data.
  dataLiveDate: null,

  // Event tracking — Cloudflare Worker URL (null to disable, see README Step 9)
  trackUrl: null,

  // Cloudflare Web Analytics (null to disable, see README Step 8)
  cfAnalyticsToken: null,

  // Contact email domain — auto-generates sb{itemLabel}week{year}@{domain}
  // Set null to hide the contact link in the About modal
  contactDomain: null,

  // Tag filters — category filters shown in the search/filter menu.
  // Each key must match a boolean property on restaurant objects in your data file.
  // Example: if you define { key: "vegetarian", ... }, each restaurant needs vegetarian: true/false.
  // Icons can be emoji strings ("🌱") or SVG filenames ("icon-vegetarian.svg") in the repo root.
  tagFilters: [
    // { key: "vegetarian", icon: "🌱", label: "Vegetarian" },
    // { key: "glutenFree", icon: "🚫", label: "Gluten Free" },
  ],

  // Hours filters — time-of-day filters (hidden until hours.json loads, see README Step 11)
  hoursFilters: [
    { key: "open", icon: "🟢", label: "Open Now" },
    { key: "lunch", icon: "☀️", label: "Lunch" },
    { key: "dinner", icon: "🌙", label: "Dinner" },
  ],

  // Google Places API key — documentation only, actual key goes in GitHub Secrets
  googlePlacesApiKey: null,
};

// Next event promo (shown in off-season banner). null for generic "check back" message.
THEME.nextEvent = null;

// Participation history — restaurant name -> first year it joined this event.
// Powers the returning-restaurant badge (shows at 2+ years). Names must match
// the data file exactly, minus any " (Location)" suffix. Generated by
// scripts/registry.py pull when using the shared restaurant registry.
THEME.firstYearByName = {};
